### ISSUE TITLE
Doesn't work when using more than one UIBarButtonItem on UINavigationItem

### ISSUE THREAD

**Issue by guigui2207** [mikeMTOL/UIBarButtonItem-Badge#12]
Hi,

I explain quickly my issue : i have two UIBarButtonItem added on a UINavigationItem : 

self.navigationItem.rightBarButtonItems =
    [NSArray arrayWithObjects:navRightButton, right2AddBarButtonItem, nil];

This allows me to have more than one button on the right hand side of the screen.

If i add a button made with your component, the badge doesn't appear.

If i do it the right way (only one button added via : 
self.navigationItem.rightBarButtonItem = navRightButton;

it works like a charm...

Hope this a small adaptation...coz i find you'r component very convenient and well made...and i would really enjoy to use it

Thanks

**Comment by guigui2207** [comment]
My mistake, was doing things the wrong way, it works perfectly...thanks

**Comment by jhickmanEB** [comment]
FYI - Detailed answer posted in #27.
