### ISSUE TITLE
IOS 11.2: BarButtonItem Badge is not working

### ISSUE THREAD

**Issue by mittalkamal29** [mikeMTOL/UIBarButtonItem-Badge#37]
Hi,

I have used that code but it is not working in IOS 11.2 for bar button item. Can you please check that issue and update it?

Thanks

**Comment by alwinlazar** [comment]
Any update

**Comment by jkpang** [comment]
Have try PPBadgeView: https://github.com/jkpang/PPBadgeView

**Comment by phunguyenquang** [comment]
On iOS 11, the `view` may not be valid anymore -> superview is not initialized -> cannot add the badge as subview.
But it works if you set custom view for `UIBarButtonItem`.
So you just need to initialize the `UIBarButtonItem` with a button as custom view, it will work.
