### ISSUE TITLE
Unable to set badgeOriginX and badgeOriginY (swift)

### ISSUE THREAD

**Issue by fishfisher** [mikeMTOL/UIBarButtonItem-Badge#9]
Hello, and thank you for this creation!
I'm using UIBarButtonItem-Badge with Swift and I can't seem to set the origin of the badge. It has no effect on the badge.

let button = UIBarButtonItem(image: buttonImage, style: .Plain, target: self, action: "buttonAction:")
button.shouldHideBadgeAtZero = true
button.badgeOriginX = -20

If I change it in badgeInit it works, but want to avoid modifying the original code.

After NSLogg'ing updateBadgeFrame it looks like it updates twice, the second time with the default value:
2015-03-04 12:59:00.367 myApp[123] Update badge frame x: -20.000000
2015-03-04 12:59:00.367 myApp[123] Update badge frame x: 24.000000

Thanks!

**Comment by fishfisher** [comment]
After further digging I think I've found the reason:

The badge is initially 0 and self.badge is therefore removed. When a new value is set, setBadgeValue: does a new badgeInit (because the badge was removed on 0) and resets to the default values.

**Comment by mikeMTOL** [comment]
hmm good catch. Let me look at it and get back to you

**Comment by mikeMTOL** [comment]
Ok I've pushed changes that should fix this behaviour. MasterViewController is now exercising the badge to go from visible->hidden->visible again

**Comment by fishfisher** [comment]
That did it! Good work. Keep it up!

**Comment by mikeMTOL** [comment]
cool, closing the issue.
